import { test, expect } from "@playwright/test";
import catalog from "../src/data/music/catalog.json" with { type: "json" };

test("names reveal progressively, history stays on projector and survives ending", async ({page,context}) => {
  await context.route(/youtube\.com\/iframe_api/, route=>route.abort());
  await page.goto("./");
  await page.getByRole("button",{name:"Ferramentas",exact:true}).click();
  await page.locator("summary",{hasText:"Sorteio"}).click();
  const tool=page.locator("details").filter({has:page.locator("summary",{hasText:"Sorteio"})});
  await tool.getByRole("combobox").selectOption("names");
  await tool.getByLabel("Um nome por linha").fill("Ana\nJoão\nMaria\nEduardo\nPedro\nLucas\nPaulo");
  await tool.getByLabel("Quantidade").fill("3");
  await tool.getByRole("button",{name:"Sortear",exact:true}).click();
  const winners=await tool.locator(".draw-results span").allTextContents();
  expect(new Set(winners).size).toBe(3);
  await expect(page.getByTestId("live-monitor")).toContainText("Nenhum conteúdo");
  await tool.getByRole("button",{name:"Preparar",exact:true}).click();
  const popup=page.waitForEvent("popup");
  await page.getByRole("button",{name:"Abrir projeção",exact:true}).click();
  const display=await popup;
  await page.getByRole("button",{name:"Colocar no ar",exact:true}).click();
  await expect(display.locator(".draw-stage")).toHaveAttribute("data-phase","drawing");
  const first=await display.locator(".draw-winner").textContent();
  await expect(display.locator(".draw-winner")).not.toHaveText(first!);
  await expect(display.locator(".draw-stage")).toHaveAttribute("data-phase","revealed");
  await expect(display.locator(".draw-winner")).toHaveText(winners[0]);
  await expect(display.locator(".draw-status")).toContainText("3 de 3",{timeout:10000});
  await expect(display.locator(".draw-stage")).toHaveAttribute("data-phase","revealed");
  await expect(display.locator(".draw-history-grid span")).toHaveText(winners.slice(0,2));
  await expect(display.locator(".draw-winner")).toHaveText(winners[2]);
  await display.screenshot({path:"test-results/draw-projector-names.png"});
  page.once("dialog",dialog=>dialog.accept());
  await page.getByRole("button",{name:"Encerrar",exact:true}).click();
  await expect(tool.locator(".operator-draw-history")).toContainText(winners.join(" · "));
  await page.reload();
  await page.getByRole("button",{name:"Ferramentas",exact:true}).click();
  await page.locator("summary",{hasText:"Sorteio"}).click();
  await expect(tool.locator(".operator-draw-history")).toContainText(winners.join(" · "));
  await tool.getByRole("button",{name:"Preparar histórico sem animação"}).click();
  await page.getByRole("button",{name:"Colocar no ar",exact:true}).click();
  await expect(display.locator(".draw-winner")).toHaveText(winners[2]);
  await expect(display.locator(".draw-stage")).toHaveAttribute("data-phase","revealed");
});

test("large catalog browses, searches and prepares without changing Live", async ({page,context}) => {
  await context.route(/youtube\.com\/iframe_api/,route=>route.abort());
  await page.goto("./");
  await page.getByRole("button",{name:"Músicas",exact:true}).click();
  await expect(page.locator(".music-album")).toHaveCount(catalog.collections.filter(c=>c.group==="youth").length);
  await page.getByRole("button",{name:/Ministério Jovem 2006/}).click();
  await expect(page.locator(".catalog-track")).toHaveCount(10);
  await page.locator(".catalog-track").filter({hasText:"Falar com Deus"}).locator(".content-row button").first().click();
  await expect(page.getByTestId("preview-monitor")).toContainText("Falar com Deus");
  await expect(page.getByTestId("preview-monitor")).toContainText("2006");
  await expect(page.getByTestId("live-monitor")).toContainText("Nenhum conteúdo");
  await page.locator(".catalog-track").filter({hasText:"Falar com Deus"}).getByTitle("Adicionar ao roteiro").click();
  await expect(page.locator(".service-panel")).toContainText("Falar com Deus");
  await page.getByRole("button",{name:"Colocar no ar",exact:true}).click();
  await page.getByLabel("Buscar no catálogo musical").fill("adoradores 4 estou aqui");
  await expect(page.locator(".catalog-track")).toHaveCount(1);
  await page.locator(".catalog-track .content-row button").first().click();
  await expect(page.getByTestId("live-monitor")).toContainText("Falar com Deus");
  await expect(page.getByTestId("preview-monitor")).toContainText("Estou aqui");
  await page.getByRole("button",{name:"Adoração Infantil",exact:true}).click();
  expect(await page.locator(".music-album").count()).toBeGreaterThan(10);
  await page.getByRole("button",{name:"Ofertas / Doxologia",exact:true}).click();
  expect(await page.locator(".catalog-track").count()).toBeGreaterThan(15);
  await page.screenshot({path:"test-results/music-library-offering.png"});
  expect(await page.locator(".music-catalog iframe").count()).toBe(0);
});
